INSERT INTO `menu` VALUES (4, 'javascript:;', '系统设置', '', 1, 'icon-settings', 0, 19);
INSERT INTO `menu` VALUES (5, 'auth/index', '权限管理', '', 1, 'glyphicon glyphicon-tasks', 4, 15);
INSERT INTO `menu` VALUES (8, 'site/index', '控制面板', '控制面板', 1, 'icon-home', 0, 0);
INSERT INTO `menu` VALUES (9, 'menu/index', '菜单管理', '', 1, NULL, 4, 15);
INSERT INTO `menu` VALUES (10, 'javascript:;', '用户管理', '', 1, 'icon-users', 0, 12);
INSERT INTO `menu` VALUES (23, 'user/index', '用户列表', '', 1, '', 10, 20);
INSERT INTO `menu` VALUES (25, 'javascript:;', '活动管理', '', 1, '', 0, 3);
INSERT INTO `menu` VALUES (26, 'activity/list', '活动列表', '', 1, '', 25, 1);
INSERT INTO `menu` VALUES (27, 'javascript:;', '设备管理', '', 1, '', 0, 4);
INSERT INTO `menu` VALUES (28, 'devices/list', '设备列表', '', 1, '', 27, 1);
